// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bhs_gibbs_rcpp
List bhs_gibbs_rcpp(const arma::vec& y, const arma::mat& X, const arma::mat& Rinv, int nmcmc, int burn, int thin, double prior_var_beta, double prior_ig_a, double prior_ig_b, Rcpp::Nullable<NumericVector> seed_);
RcppExport SEXP _edaphos_bhs_gibbs_rcpp(SEXP ySEXP, SEXP XSEXP, SEXP RinvSEXP, SEXP nmcmcSEXP, SEXP burnSEXP, SEXP thinSEXP, SEXP prior_var_betaSEXP, SEXP prior_ig_aSEXP, SEXP prior_ig_bSEXP, SEXP seed_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Rinv(RinvSEXP);
    Rcpp::traits::input_parameter< int >::type nmcmc(nmcmcSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< double >::type prior_var_beta(prior_var_betaSEXP);
    Rcpp::traits::input_parameter< double >::type prior_ig_a(prior_ig_aSEXP);
    Rcpp::traits::input_parameter< double >::type prior_ig_b(prior_ig_bSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<NumericVector> >::type seed_(seed_SEXP);
    rcpp_result_gen = Rcpp::wrap(bhs_gibbs_rcpp(y, X, Rinv, nmcmc, burn, thin, prior_var_beta, prior_ig_a, prior_ig_b, seed_));
    return rcpp_result_gen;
END_RCPP
}
// quantum_kernel_rcpp
Rcpp::NumericMatrix quantum_kernel_rcpp(Rcpp::NumericMatrix X, Rcpp::Nullable<Rcpp::NumericMatrix> Y_opt, int reps);
RcppExport SEXP _edaphos_quantum_kernel_rcpp(SEXP XSEXP, SEXP Y_optSEXP, SEXP repsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type Y_opt(Y_optSEXP);
    Rcpp::traits::input_parameter< int >::type reps(repsSEXP);
    rcpp_result_gen = Rcpp::wrap(quantum_kernel_rcpp(X, Y_opt, reps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_edaphos_bhs_gibbs_rcpp", (DL_FUNC) &_edaphos_bhs_gibbs_rcpp, 10},
    {"_edaphos_quantum_kernel_rcpp", (DL_FUNC) &_edaphos_quantum_kernel_rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_edaphos(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
