// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// quantum_kernel_rcpp
Rcpp::NumericMatrix quantum_kernel_rcpp(Rcpp::NumericMatrix X, Rcpp::Nullable<Rcpp::NumericMatrix> Y_opt, int reps);
RcppExport SEXP _edaphos_quantum_kernel_rcpp(SEXP XSEXP, SEXP Y_optSEXP, SEXP repsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type Y_opt(Y_optSEXP);
    Rcpp::traits::input_parameter< int >::type reps(repsSEXP);
    rcpp_result_gen = Rcpp::wrap(quantum_kernel_rcpp(X, Y_opt, reps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_edaphos_quantum_kernel_rcpp", (DL_FUNC) &_edaphos_quantum_kernel_rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_edaphos(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
