# Package-level Zenodo release helper (v2.1.0).
#
# The edaphos package ships multiple inst/extdata bundles that are
# re-generated by `data-raw/*.R` runners but also belong in a single
# Zenodo-deposit bundle so a paper citation can point to a permanent
# DOI with the full provenance of every numerical result.
#
# `edaphos_zenodo_release(output_dir, ...)` bundles:
#   - The compiled package tarball (optional, user-supplied or built
#     with `devtools::build()` on demand)
#   - Every inst/extdata/*.rds + *.jsonl shipped with the package
#   - A NEWS snapshot
#   - A CITATION.cff copy
#   - A DataCite-compatible metadata.json
#   - A README with file manifest + SHA-256 checksums
#
# Upload is manual at https://zenodo.org/deposit/new.  We never embed
# the user's personal-access token in the package.

#' Build a Zenodo-ready release bundle for the edaphos package
#'
#' @param output_dir Directory to create (overwritten if it exists).
#' @param include_tarball Logical.  If `TRUE` (default), also run
#'   [`devtools::build()`] and drop the resulting `.tar.gz` into the
#'   bundle.  Requires the `devtools` package.
#' @param title Deposit title; defaults to a sensible package-level
#'   string with the current version.
#' @param description Free-text description (HTML allowed).  Defaults
#'   to the package DESCRIPTION's Description field.
#' @param authors Data frame with `family_name`, `given_name`,
#'   optional `orcid`, optional `affiliation`.  Defaults to a single-
#'   author entry for the package maintainer.
#' @param keywords Character vector of Zenodo keywords.
#' @param zip Logical; also produce a zip archive.  Default `TRUE`.
#'
#' @return Invisibly, the path of the created directory.
#' @export
edaphos_zenodo_release <- function(
    output_dir,
    include_tarball = TRUE,
    title           = NULL,
    description     = NULL,
    authors         = NULL,
    keywords        = c("digital soil mapping", "causal inference",
                          "foundation models", "quantum machine learning",
                          "Cerrado", "pedometrics"),
    zip             = TRUE) {
  stopifnot(is.character(output_dir), length(output_dir) == 1L)
  if (dir.exists(output_dir)) unlink(output_dir, recursive = TRUE)
  dir.create(output_dir, recursive = TRUE)

  pkg_version <- as.character(utils::packageVersion("edaphos"))
  if (is.null(title))
    title <- sprintf("edaphos %s -- Disruptive algorithms for Digital Soil Mapping",
                      pkg_version)
  if (is.null(authors)) {
    authors <- data.frame(
      family_name = "Rodrigues", given_name = "Hugo",
      orcid       = "0000-0002-8070-8126",
      affiliation = "University of Sao Paulo",
      stringsAsFactors = FALSE
    )
  }
  if (is.null(description)) {
    description <- paste0(
      "<p>edaphos is a research-grade R package implementing frontier ",
      "algorithms for Digital Soil Mapping (DSM) across six research ",
      "pillars: Causal AI with LLM-driven Knowledge Graphs, ",
      "Physics-Informed ML, 4D Pedometry, Foundation Models, ",
      "Autonomous Active Learning, and Quantum ML, plus cross-pillar ",
      "bridges (Pilar 1 x Pilar 4 IV, Pilar 4 x Pilar 6 quantum-foundation) ",
      "and a unified uncertainty API. Version ", pkg_version, ".</p>"
    )
  }

  # -- 1. Compile the extdata bundles ----------------------------------
  extdata_src <- system.file("extdata", package = "edaphos")
  if (!nzchar(extdata_src) || !dir.exists(extdata_src))
    extdata_src <- file.path("inst", "extdata")
  if (!dir.exists(extdata_src))
    stop("inst/extdata not found -- run from package root.", call. = FALSE)

  bundle_files <- list.files(extdata_src,
                               pattern = "\\.(rds|jsonl)$",
                               full.names = TRUE)
  bundles_sub <- file.path(output_dir, "bundles")
  dir.create(bundles_sub)
  file.copy(bundle_files, bundles_sub, overwrite = TRUE)

  # -- 2. Snapshot CITATION.cff + NEWS.md ------------------------------
  for (f in c("CITATION.cff", "NEWS.md", "README.md")) {
    src <- if (file.exists(f)) f
           else system.file(f, package = "edaphos")
    if (nzchar(src) && file.exists(src)) {
      file.copy(src, file.path(output_dir, f), overwrite = TRUE)
    }
  }

  # -- 3. Package tarball (optional) -----------------------------------
  # Use getExportedValue() to keep devtools in Suggests-only.
  # R CMD check doesn't flag this as an undeclared `::` reach.
  if (isTRUE(include_tarball)) {
    if (!requireNamespace("devtools", quietly = TRUE)) {
      message("[zenodo] devtools not available; skipping tarball build.")
    } else {
      build_fn <- tryCatch(getExportedValue("devtools", "build"),
                             error = function(e) NULL)
      if (!is.null(build_fn)) {
        tryCatch(
          do.call(build_fn, list(path = output_dir,
                                   vignettes = FALSE, quiet = TRUE)),
          error = function(e) {
            message("[zenodo] tarball build failed: ", conditionMessage(e))
          }
        )
      }
    }
  }

  # -- 4. DataCite metadata.json ---------------------------------------
  metadata <- list(
    metadata = list(
      title              = title,
      upload_type        = "software",
      description        = description,
      creators           = lapply(seq_len(nrow(authors)), function(i) {
        cr <- list(name = sprintf("%s, %s",
                                    authors$family_name[i],
                                    authors$given_name[i]))
        if (!is.na(authors$orcid[i]))        cr$orcid       <- authors$orcid[i]
        if (!is.na(authors$affiliation[i])) cr$affiliation <- authors$affiliation[i]
        cr
      }),
      keywords           = as.list(keywords),
      access_right       = "open",
      license            = "mit",
      version            = pkg_version,
      related_identifiers = list(
        list(relation = "isVersionOf",
             identifier = "10.5281/zenodo.19683708",
             resource_type = "software",
             scheme = "doi")
      )
    )
  )
  jsonlite::write_json(metadata,
                        file.path(output_dir, "metadata.json"),
                        pretty = TRUE, auto_unbox = TRUE)

  # -- 5. Manifest with SHA-256 checksums ------------------------------
  manifest_rows <- list()
  for (f in list.files(output_dir, recursive = TRUE, full.names = TRUE)) {
    sha <- if (requireNamespace("digest", quietly = TRUE)) {
      digest::digest(file = f, algo = "sha256")
    } else NA_character_
    manifest_rows[[length(manifest_rows) + 1L]] <- data.frame(
      path   = sub(paste0("^", normalizePath(output_dir, winslash = "/"), "/"),
                    "", normalizePath(f, winslash = "/")),
      bytes  = file.size(f),
      sha256 = sha,
      stringsAsFactors = FALSE
    )
  }
  manifest <- do.call(rbind, manifest_rows)
  utils::write.csv(manifest, file.path(output_dir, "manifest.csv"),
                     row.names = FALSE)

  # -- 6. Human-readable README ----------------------------------------
  readme <- c(
    sprintf("# %s", title),
    "",
    sprintf("**Package version:** %s  |  **Release date:** %s",
            pkg_version, as.character(Sys.Date())),
    "",
    "## Bundle contents",
    "",
    "```",
    paste(" -", manifest$path),
    "```",
    "",
    "## Files at a glance",
    "- `bundles/*.rds / *.jsonl` -- pre-computed scientific artefacts",
    "  shipped with every edaphos install (see `inst/extdata/` in source).",
    "- `CITATION.cff` -- bibliographic metadata (CFF 1.2.0).",
    "- `NEWS.md` -- full changelog back to v0.1.0.",
    "- `README.md` -- copy of the package-level README.",
    "- `metadata.json` -- DataCite-compatible Zenodo deposit metadata.",
    "- `manifest.csv` -- SHA-256 checksums for every file.",
    "- `edaphos_<version>.tar.gz` -- R package tarball",
    "  (present if `include_tarball = TRUE`).",
    "",
    "## How to deposit",
    "",
    "1. Open <https://zenodo.org/deposit/new>.",
    "2. Upload the zip archive or drag-and-drop individual files.",
    "3. Copy fields from `metadata.json` into the Zenodo web form.",
    "4. Save and publish; record the minted DOI in the package's",
    "   `CITATION.cff` and `.zenodo.json`.",
    "",
    "## How to cite",
    "",
    sprintf("> Rodrigues, H. (%d). *edaphos* (Version %s) [Software]. Zenodo. DOI: [concept] 10.5281/zenodo.19683708",
            as.integer(format(Sys.Date(), "%Y")), pkg_version),
    ""
  )
  writeLines(readme, file.path(output_dir, "ZENODO-README.md"))

  # -- 7. Zip (optional) -----------------------------------------------
  if (isTRUE(zip)) {
    zip_path <- paste0(output_dir, ".zip")
    if (file.exists(zip_path)) file.remove(zip_path)
    old_wd <- getwd(); on.exit(setwd(old_wd), add = TRUE)
    setwd(dirname(output_dir))
    utils::zip(basename(zip_path), basename(output_dir),
                flags = "-r9Xq")
  }

  message(sprintf("[zenodo] release bundle ready: %s", output_dir))
  message(sprintf("[zenodo] %d files, total %.1f MB",
                   nrow(manifest),
                   sum(manifest$bytes, na.rm = TRUE) / 1024^2))
  invisible(output_dir)
}
