# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

quantum_kernel_rcpp <- function(X, Y_opt, reps) {
    .Call(`_edaphos_quantum_kernel_rcpp`, X, Y_opt, reps)
}

