# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bhs_gibbs_rcpp <- function(y, X, Rinv, nmcmc, burn, thin, prior_var_beta, prior_ig_a, prior_ig_b, seed_) {
    .Call(`_edaphos_bhs_gibbs_rcpp`, y, X, Rinv, nmcmc, burn, thin, prior_var_beta, prior_ig_a, prior_ig_b, seed_)
}

quantum_kernel_rcpp <- function(X, Y_opt, reps) {
    .Call(`_edaphos_quantum_kernel_rcpp`, X, Y_opt, reps)
}

